[package]
name = "zcash_script"
version = "0.1.6-alpha.0"
authors = ["Tamas Blummer <tamas.blummer@gmail.com>", "Zcash Foundation <zebra@zfnd.org>"]
license = "Apache-2.0"
readme = "README.md"
build = "build.rs"
edition = "2018"
description = "ffi bindings to zcashd's zcash_script library"
documentation = "https://docs.rs/zcash_script"
repository = "https://github.com/ZcashFoundation/zcash_script"
include = [
    "/.github/workflows/ci.yml",
    "/.gitignore",
    "/.gitmodules",
    "Cargo.toml",
    "/LICENSE",
    "/README.md",
    "build.rs",
    "depend/check_uint128_t.c",
    "src/blake2b.rs",
    "src/lib.rs",
    "/depend/zcash/src/script/zcash_script.h",
    "/depend/zcash/src/script/zcash_script.cpp",
    "/depend/zcash/src/utilstrencodings.cpp",
    "/depend/zcash/src/uint256.cpp",
    "/depend/zcash/src/pubkey.cpp",
    "/depend/zcash/src/hash.cpp",
    "/depend/zcash/src/primitives/transaction.cpp",
    "/depend/zcash/src/crypto/ripemd160.cpp",
    "/depend/zcash/src/crypto/sha1.cpp",
    "/depend/zcash/src/crypto/sha256.cpp",
    "/depend/zcash/src/crypto/sha512.cpp",
    "/depend/zcash/src/crypto/hmac_sha512.cpp",
    "/depend/zcash/src/script/interpreter.cpp",
    "/depend/zcash/src/script/script.cpp",
    "/depend/zcash/src/script/script_error.cpp",
    "/depend/zcash/src",
    "/depend/zcash/src/rust/include/",
    "/depend/zcash/src/secp256k1/include",
    "/depend/zcash/src/secp256k1",
    "/depend/zcash/src/support/cleanse.cpp",
    "/depend/zcash/src/support/cleanse.h",
]

[lib]
name = "zcash_script"
path = "src/lib.rs"

[features]
external-secp = []

[dependencies]
blake2b_simd = "0.5.10"
halo2 = "0.1.0-beta.1"
incrementalmerkletree = "0.1"
libc = "0.2"
memuse = "0.2"
orchard = "0.0"
rand_core = "0.6"
tracing = "0.1"
zcash_note_encryption = "0.0"
zcash_primitives = "0.5"

[build-dependencies]
cc = { version = ">= 1.0.36", features = ["parallel"] }
bindgen = "0.58"

[dev-dependencies]
rustc-serialize = "0.3"
hex = "0.4.2"
lazy_static = "1.4.0"

[[package.metadata.release.pre-release-replacements]]
file = "CHANGELOG.md"
search = "Unreleased"
replace="{{version}}"

[[package.metadata.release.pre-release-replacements]]
file = "src/lib.rs"
search = "#!\\[doc\\(html_root_url.*"
replace = "#![doc(html_root_url = \"https://docs.rs/{{crate_name}}/{{version}}\")]"
exactly = 1

[[package.metadata.release.pre-release-replacements]]
file = "CHANGELOG.md"
search = "\\.\\.\\.HEAD"
replace="...{{tag_name}}"
exactly = 1

[[package.metadata.release.pre-release-replacements]]
file = "CHANGELOG.md"
search = "ReleaseDate"
replace="{{date}}"
exactly=1

[[package.metadata.release.pre-release-replacements]]
file="CHANGELOG.md"
search="<!-- next-header -->"
replace="<!-- next-header -->\n\n## [Unreleased] - ReleaseDate"
exactly=1

[[package.metadata.release.pre-release-replacements]]
file="CHANGELOG.md"
search="<!-- next-url -->"
replace="<!-- next-url -->\n[Unreleased]: https://github.com/ZcashFoundation/{{crate_name}}/compare/{{tag_name}}...HEAD"
exactly=1

[patch.crates-io]
# Copied from Zebra after PR #3057

# TODO: replace with upstream orchard when these changes are merged
# https://github.com/ZcashFoundation/zebra/issues/3056
orchard = { git = "https://github.com/ZcashFoundation/orchard.git", rev = "568e24cd5f129158375d7ac7d98c89ebff4f982f" }

# TODO: remove these after a new librustzcash release.

# These are librustzcash git requirements specified in its workspace Cargo.toml,
# that we must replicate here
incrementalmerkletree = { git = "https://github.com/zcash/incrementalmerkletree.git", rev = "b7bd6246122a6e9ace8edb51553fbf5228906cbb" }
# Replaced by the ZcashFoundation fork above
#orchard = { git = "https://github.com/zcash/orchard.git", rev = "2c8241f25b943aa05203eacf9905db117c69bd29" }

# These are librustzcash file requirements specified in its workspace Cargo.toml,
# that we must replace with git requirements
zcash_note_encryption = { git = "https://github.com/zcash/librustzcash.git", rev = "53d0a51d33a421cb76d3e3124d1e4c1c9036068e" }

# These patches are not strictly required,
# but they help avoid duplicate dependencies
zcash_primitives = { git = "https://github.com/zcash/librustzcash.git", rev = "53d0a51d33a421cb76d3e3124d1e4c1c9036068e" }
